version: '3.4'

services:
  mssql:
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql/data
    environment:
        SA_PASSWORD: "f#Vf8sYBF2"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer" # "Express"

volumes:
  mssql-volume: